source "https://rubygems.org"

# Fastlane version - update as needed
# You can check your installed version with: fastlane --version
gem "fastlane", ">= 2.229.0"

plugins_path = File.join(File.dirname(__FILE__), 'fastlane', 'Pluginfile')
eval_gemfile(plugins_path) if File.exist?(plugins_path)

