name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint
      - name: Lint Python
        run: |
          if ls *.py 1> /dev/null 2>&1; then pylint *.py || true; fi
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - name: Install JS dependencies
        run: |
          if [ -f package.json ]; then npm ci; fi
      - name: Lint JS
        run: |
          if [ -f package.json ]; then npx eslint js/ || true; fi
      - name: Run tests
        run: |
          echo "No automated tests defined yet. Add tests to enable this step."
